---

- name: Detect empty disks
  shell: >
    {{ lvm_extend_cmd_new }}
  register: lvm_extend_disks
  changed_when: false

- include: vg.yaml
  with_dict: "{{ lvm_extend_config }}"
  loop_control:
    loop_var: lvm_extend_vg
