---

- name: Install LVM tools
  package:
    name: "{{ lvm_extend_pkg }}"
  tags:
    - lvm_extend_pkg

- name: Detect empty disks
  shell: >
    {{ lvm_extend_cmd_new }}
  register: lvm_extend_disks
  changed_when: false

- include_tasks: vg.yaml
  with_dict: "{{ lvm_extend_config }}"
  loop_control:
    loop_var: lvm_extend_vg
